# Generated by Django 3.1.5 on 2021-01-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_remove_prestamo_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.libro'),
        ),
    ]
