# Generated by Django 3.1.5 on 2021-01-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_auto_20210111_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
    ]
